export const APP_ACTION_TEST = 'APP_ACTION_TEST'

// app
export const APP_INIT_REQUEST = 'APP_INIT_REQUEST';
export const APP_INIT_REQUEST_SUCCESS = 'APP_INIT_REQUEST_SUCCESS';
export const APP_INIT_REQUEST_FAILED = 'APP_INIT_REQUEST_FAILED';
export const APP_USERINFO_REQUEST = 'APP_USERINFO_REQUEST';
export const APP_USERINFO_REQUEST_SUCCESS = 'APP_USERINFO_REQUEST_SUCCESS';